version: '3.3'
services:
  decadevs_docker:
    container_name: decadevs-docker-edema
    image: decadevs-docker-edema
    build: ./
    ports:
      - "8532:8080"
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    ports:
      - "3340:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: edema
      MYSQL_USER: edema
      MYSQL_DATABASE: edemadb
      MYSQL_PASSWORD: edema